language: php

php:
  - 5.5
  - 5.6

install:
  - composer install

script:
  - php vendor/bin/codecept build
  - php vendor/bin/codecept run --coverage --coverage-xml -vvv

after_script:
  - php vendor/bin/coveralls