language: php

php:
  - 5.5
  - 5.6

install:
  - rm composer.lock
  - composer install

script:
  - ./tests/_data/db.sh
  - php vendor/bin/codecept build
  - php vendor/bin/codecept run --coverage --coverage-xml

after_script:
  - php vendor/bin/coveralls
